### PR TITLE
Updated css on Donate/Contacts section

### PR DESCRIPTION
**Pull request by SKibreab**
Resolved the following issue:

https://github.com/spicygreenbook/greenbook-app/issues/21

### CODE REVIEW

**Comment by pleaseshutup** [comment]
It looks like your pull request does not include stripe.css changes and the means of importaing the stylesheet does not work with react native/mobile apps. You likely only needed to edit stripe.css and make no other changes to accomplish this from what I can see (but i may be wrong, i'm just guessing)

**Comment by SKibreab** [comment]
I just saw your message about the mobile apps, working on setting the
emulators up now.  I will take a look.  I assumed since I didn't make any
chances to the stripe.css file that it wouldn't need to be in the pull
request but I will test and make the necessary changes.  Sorry about that!
Think I got a bit ahead of myself.

**Comment by pleaseshutup** [comment]
The request is to update the CSS to match the provided design. The issue was not that the CSS file failed to apply to the form. Your changes can work in regular React but not in React Native / Expo.

**Comment by pleaseshutup** [comment]
FYI this task is incomplete. I'm not sure what the mentioned PR did but it did not include any style changes.

**Pull request closed without merging**
